### ISSUE TITLE
Custom compiler flags

### ISSUE THREAD

**Issue by Nicholas-Baron** [STBoyden/ocean#1]
I am used to using `-Wall -Wextra` on my code. However, it looks like there is no way to add `-Wextra` to the compile command.

https://github.com/STBoyden/ocean/blob/58fb01a4da7b9c0bf0be277ed43021a5daea262f/src/main.rs#L123-L126

**Comment by STBoyden** [comment]
I'll at some point make it so that you can declare custom flags within Ocean.toml. For the time being, however I'll add -Wextra as a default flag.

**Comment by Nicholas-Baron** [comment]
That seems fine as a temporary thing.
`gcc` and `clang` document that `-Wextra` only enables 15 warnings, which is small compared to `-Wall`'s 50 some.

**Comment by STBoyden** [comment]
Implemented a way to add custom compiler flags in both the Ocean.toml and through the command line
